root: true
extends: eslint:recommended

parserOptions:
  ecmaVersion: 6

env:
  commonjs: true

rules:
  indent: [2, 2] # 2 spaces indentation
  max-len: [2, 80, 2]
  quotes: [2, "double"]
  semi: [2, "never"]
  no-multiple-empty-lines: [2, {"max": 1}]

  brace-style: [2, "stroustrup"]
  comma-dangle: [2, "always-multiline"]
  comma-style: [2, "last"]
  dot-location: [2, "property"]

  one-var: [2, "never"]
#  no-var: [2]
  prefer-const: [2]
  no-bitwise: [2]

  object-curly-spacing: [2, "never"]
  array-bracket-spacing: [2, "never"]
  computed-property-spacing: [2, "never"]

  space-unary-ops: [2, {"words": true, "nonwords": false}]
  keyword-spacing: [2, {"before": true, "after": true}]
  space-before-blocks: [2, "always"]
  space-before-function-paren: [2, "never"]
  space-in-parens: [2, "never"]
  spaced-comment: [2, "always"]
